#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD Socket Server
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket

case "$1" in
  start)
    echo "Starting $NAME"
    $DAEMON -d
    ;;
  stop)
    echo "Stopping $NAME"
    # BusyBox-friendly stop
    killall aesdsocket 2>/dev/null || true
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
